version: '3.8'
services:
  habits:
    container_name: mshabits
    image: looney/basic-ms
    build: ./backend/common
    volumes:
      - ./backend/habits/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    image: looney/basic-ms
    build: ./backend/common
    volumes:
      - ./backend/api-gateway/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  moods:
    container_name: msmoods
    image: looney/basic-ms
    build: ./backend/common
    volumes:
      - ./backend/moods/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  users:
    container_name: msusers
    image: looney/basic-ms
    build: ./backend/common
    volumes:
      - ./backend/users/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  sveltekit:
      container_name: sveltekit
      image: looney/sveltekit
      restart: on-failure
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000:5173
      volumes:
        - ./frontend:/usr/src/app
      networks:
        - mslooney
networks:
  mslooney:
    driver: bridge