version: '3.8'
services:
  habits:
    container_name: mshabits
    build: ./backend/habits
    volumes:
      - ./backend/habits/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./backend/api-gateway
    volumes:
      - ./backend/api-gateway/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  moods:
    container_name: msmoods
    build: ./backend/moods
    volumes:
      - ./backend/moods/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./backend/api-gateway
    volumes:
      - ./backend/api-gateway/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  users:
    container_name: msusers
    build: ./backend/users
    volumes:
      - ./backend/users/code:/usr/src/app
    networks:
      - mslooney
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  mslooney:
    driver: bridge