name: GitHub Actions Backend Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Cd to users microservice directory and run jest test
        run: cd backend/users/code && npm ci && npm test
       
