name: ESLint Checks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install Dependencies of the client
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint in /frontend
        run: npx eslint .
        working-directory: ./frontend/src

      - name: Install Dependencies of the Users microservice
        run: npm install
        working-directory: ./backend/users/code

      - name: Run ESLint users microservice
        run: npx eslint .
        working-directory: ./backend/users/code

      - name: Install Dependencies of the Habits microservice
        run: npm install
        working-directory: ./backend/habits/code

      - name: Run ESLint habits microservice
        run: npx eslint .
        working-directory: ./backend/babits/code

      - name: Install Dependencies of the Moods microservice
        run: npm install
        working-directory: ./backend/moods/code

      - name: Run ESLint moods microservice
        run: npx eslint .
        working-directory: ./backend/moods/code

      - name: Install Dependencies of the gateway
        run: npm install
        working-directory: ./backend/api-gateway/code

      - name: Run ESLint gateway
        run: npx eslint .
        working-directory: ./backend/api-gateway/code

        