name: ESLint Checks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install Dependencies of the client
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint in /frontend
        run: npx eslint .
        working-directory: ./frontend/src

      - name: Install Dependencies of the Users microservice
        run: npm install
        working-directory: ./backend/users/code

      - name: Run ESLint users microservice
        run: npx eslint .
        working-directory: ./backend/users/code