name: Test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd frontend
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test