name: Backend Unit Tests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        
      - name: Run jest tests in the users microservice
        env:
          NODE_ENV: test
        run: |
          cd backend/users/code
          npm ci
          npm run coverage-test

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./backend/users/code/coverage/coverage-summary.json
          title: My Jest Coverage Comment
          summary-title: My Summary Title
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-path: ./backend/users/code/junit.xml
          junitxml-title: My JUnit Title
