name: Backend Unit Tests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        
      - name: Run jest tests in the users microservice
        env:
          NODE_ENV: test
        run: |
          cd backend/users/code
          npm ci
          npm run coverage-test

      - name: Jest Coverage Comment for Users MS
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token:  ${{ secrets.TESTING_TOKEN }}
          coverage-summary-path: ./backend/users/code/coverage/coverage-summary.json
          title: Unit Testing Coverage - Users MS
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Tests ran
          junitxml-path: ./backend/users/code/junit.xml
          coverage-title: Details
          coverage-path: ./backend/users/code/coverage.txt

      - name: Run jest tests in the moods microservice
        env:
          NODE_ENV: test
        run: |
          cd backend/moods/code
          npm ci
          npm run coverage-test

      - name: Jest Coverage Comment for Moods MS
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token:  ${{ secrets.TESTING_TOKEN }}
          coverage-summary-path: ./backend/moods/code/coverage/coverage-summary.json
          title: Unit Testing Coverage - Moods MS
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Tests ran
          junitxml-path: ./backend/moods/code/junit.xml
          coverage-title: Details
          coverage-path: ./backend/moods/code/coverage.txt
